server:
  port: 8091
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3006/mall?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: hidoctor
    password: Hi0.doctor
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      max-wait: 60000
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
      validation-query: SELECT 1 FROM DUAL
  rabbitmq: #rabbitmq相关配置
    host: localhost
    port: 5672
    username: admin
    password: admin
mybatis:
  mapper-locations:
    - classpath:com/**/mapper/*.xml
    - classpath:dao/*.xml

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头
secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /upload/product/**
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: LTAI4GABDMGANJhW7cPnQQ54 # 访问身份验证中用到用户标识
    accessKeySecret: x8muwgIWqZ1gwzOlMWtO3fHWmEcyRY # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: luban-oss # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    callback: http://lubanbole.natapp1.cc//aliyun/oss/callback # 文件上传成功后的回调地址
    dir:
      prefix: lubanmall/images/ # 上传文件夹路径前缀

upload:
  product:
    images: D:/temp/product/images

logging:
  level:
    com.lucifer.springboot.cache.mapper: debug